name:               "KEY"
description:        "Key.log"

url:                ""
author:             "KimEunYeol"
email:              "kimeunyeol23@gmail.com"
gravatar_hash:      "9b90eb6fdc8622fd38e2886f231f91eb"
twitter:            ""
email:              "kimeunyeol23@gmail.com"
github:             "KimEunYeol"
pinterest:          ""
linkedin:           "KimEunYeol"
facebook:           "nianosrep"

disqus_shortname:   "KEY"

background:         "http://apple.wallpapersfine.com/wallpapers/original/1242x2208/w-5273.jpg"

paginate:           5
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

nav:
  - name:           "About"
    href:           "/about"
  - name:           "Post"
    href:           "/releases"

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate
